apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: generator
spec:
  selector:
    matchLabels:
      app: generator
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: generator
        role: master
        tier: backend
    spec:
      containers:
      - name: generator
        image: 387527458246/generator
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        ports:
        - containerPort: 5000
---
